### ISSUE TITLE
Pretrained weights

### ISSUE THREAD

**Issue by xdaimon** [Petachok/Vehicle-Detector#1]
Do you have pretrained weights available? If not, how computationally expensive is this to train on a dataset like http://www.gti.ssr.upm.es/data/Vehicle_database.html or https://ai.stanford.edu/~jkrause/cars/car_dataset.html ?

**Comment by Petachok** [comment]
Hello,

the network used for training and detection is Mask-Rcnn. I directed implementation to work with MS COCO dataset, thus requiring a compatible COCO annotations file that specifies masks.

you will not be able to train using the datasets you suggested.
